10 PRINT"{CLR}":FORI=0TO63:POKE832+I,0:NEXT
20 GOSUB60000
999 END
60000 DATA"       {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}       "
60001 DATA"     {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}     "
60002 DATA"    {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}    "
60003 DATA"    {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}   {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}    "
60004 DATA"   {BULLET}{BULLET}{BULLET}{BULLET}{BULLET} {BULLET}{BULLET}{BULLET} {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}   "
60005 DATA"   {BULLET}{BULLET}{BULLET}{BULLET}{BULLET} {BULLET}{BULLET}{BULLET} {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}   "
60006 DATA"   {BULLET}{BULLET}{BULLET}{BULLET}{BULLET} {BULLET}{BULLET}{BULLET} {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}   "
60007 DATA"    {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}   {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}    "
60008 DATA"    {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}    "
60009 DATA"    {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}    "
60010 DATA"    {BULLET} {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET} {BULLET}    "
60011 DATA"     {BULLET} {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET}{BULLET} {BULLET}     "
60012 DATA"     {BULLET}  {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}  {BULLET}     "
60013 DATA"      {BULLET}  {BULLET}{BULLET}{BULLET}  {BULLET}      "
60014 DATA"      {BULLET}  {BULLET}{BULLET}{BULLET}  {BULLET}      "
60015 DATA"       {BULLET}  {BULLET}  {BULLET}       "
60016 DATA"       {BULLET}  {BULLET}  {BULLET}       "
60017 DATA"        {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}        "
60018 DATA"        {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}        "
60019 DATA"        {BULLET}{BULLET}{BULLET}{BULLET}{BULLET}        "
60020 DATA"         {BULLET}{BULLET}{BULLET}         "
60100 V=53248:POKEV,200:POKEV+1,100:POKEV+21,1:POKEV+39,14:POKE2040,13
60105 POKEV+23,1:POKEV+29,1
60110 FORI=0TO20:READA$:FORK=0TO2:T=0:FORJ=0TO7:B=0
60140 IFMID$(A$,J+K*8+1,1)="{BULLET}"THENB=1
60150 T=T+B*2^(7-J):NEXT:PRINT T;: POKE832 + I*3+K,T:NEXT:PRINT:NEXT
60200 RETURN