10 OPEN 1, 1, 1, "TEST": REM CREATEA FILE
20 CMD 1: REM OUTPUT TO TAPE FilE, NOT SCREEN
30 FOR l = 1 TO 100
40 PRINT l: REM PUTS NUMBER IN TAPE BUFFER
50 NEXT
60 PRINT# 1: REM UNLISTEN
70 CLOSE 1: REM WRITE UNFINISHED BUFFER, PROPERLYFINISH
